### ISSUE TITLE
iotedge binary does not links libssl and libcrypto

### ISSUE THREAD

**Issue by daviur** [Azure/azure-iotedge#11]
I am trying to run the iooedge daemon on ubuntu 18.04 but it fails.

Seeing the output of "ldd itoedge" I can see it does not link libssl.so.10 and libcrypto.so.10. 

I certainly can create a simlink against libssl.so.1.0.0/libcrypto.so.1.0.0 but I wonder why the naming differs.

Any insights?

**Comment by chipalost** [comment]
Hi @daviur, please post this on the issues page for the IoT Edge open source project (https://github.com/azure/iotedge/issues). That is the source of our team's triage. We do not regularly check this page.
We understand that it is initially confusing to have two GitHub repos; however it is necessary for legal purposes.
Azure IoT Edge, open source project - https://github.com/azure/iotedge/
Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We try and do our coding in the open source project so that is why we request that issues are reported there.
