### ISSUE TITLE
Moby-engine 3.0.2 fails in starting IoT Edge runtime

### ISSUE THREAD

**Issue by tedchina** [Azure/azure-iotedge#14]
**Steps to reproduce the issue:**
1. On a physical machine with Amd64 and Ubuntu 18.04, uninstall the previously installed `docker-ce`.
2. Install Moby and Azure-IoT-Edge according to the instructions at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux
2. After install/config/restart `iotedge`, `edgeAgent` is found unable to be started because of failure in dialing `dial unix:///run/containerd/containerd.sock`.
3. Uninstall `moby-engine` and `moby-cli`, and then reinstall `docker-ce` and `docker-ce-cli`. Then the `iotedge` installed/configured in the preceding step can now be successfully started.

**Output of `docker version`:**
```
sudo apt show docker-ce
Package: docker-ce
Version: 5:18.09.0~3-0~ubuntu-bionic

sudo apt show moby-engine
Package: moby-engine
Version: 3.0.2
```
Linked issue: https://github.com/moby/moby/issues/38461

**Comment by chipalost** [comment]
Hi @tedchina, please post this on the issues page for the IoT Edge open source project (https://github.com/azure/iotedge/issues). That is the source of our team's triage. We do not regularly check this page.
We understand that it is initially confusing to have two GitHub repos; however it is necessary for legal purposes.
Azure IoT Edge, open source project - https://github.com/azure/iotedge/
Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We try and do our coding in the open source project so that is why we request that issues are reported there.
