### ISSUE TITLE
How to go to end of the logs in iotedge module

### ISSUE THREAD

**Issue by gadgetman4u** [Azure/azure-iotedge#15]
I have an iotedge module and to get the logs, I type:

iotedge logs <module>

However, when I do that, it runs through the entire log and if it is a large log, then you have to wait a long time before you see the end of that log.  I tried to pipe the command to a txt file, but it seems to just hang.

How can I see the end of the log for a particular module?

**Comment by chipalost** [comment]
Hi @gadgetman4u, this sounds like more of a question than bug report. We use GitHub issues for bugs and StackOverflow tagged with #azure-iot-edge for questions. 

For bug reports, please post on the issues page for the IoT Edge open source project (https://github.com/azure/iotedge/issues). That is the source of our team's triage. We do not regularly check this page.
We understand that it is initially confusing to have two GitHub repos; however it is necessary for legal purposes.
Azure IoT Edge, open source project - https://github.com/azure/iotedge/
Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We try and do our coding in the open source project so that is why we request that issues are reported there.
