### ISSUE TITLE
Failure on Edge Hub and messages get stuck while sending messages upstream

### ISSUE THREAD

**Issue by pratson20** [Azure/azure-iotedge#16]
Hi,

I am facing issue while running modules on Edge runtime. Device is running perfectly fine for  7-10 days but after that message got stuck and seeing some exception in EdgeHub.

Below is the device configuration-
OS- Ubuntu 16.0.4
DPS- TPM on Aaeon Gateway
Edge Runtime Version- 1.0.5
Offline Capability for Message storage- 24 hours
Failure status- Message get stuck after running for 7-10 days and sometimes more. Sometimes in a day also.
Gateway Configuration- 4GB RAM and 32 GB SSD
Solution- Manually delete all docker images- "sudo docker rm -f edgeHub edgeAgent mymodule". It starts again after executing this command.

Can you please let me know the solution to resolve this issue. It is completely blocker for me to implement Azure Edge on Gateway.

[failed_logs_edgeAgent_10_days_08_01_2019.txt](https://github.com/Azure/azure-iotedge/files/2746847/failed_logs_edgeAgent_10_days_08_01_2019.txt)
[failed_logs_edgeAgent_05012019.txt](https://github.com/Azure/azure-iotedge/files/2746848/failed_logs_edgeAgent_05012019.txt)
[failed_logs_edgeHub_10_days_08_01_2019.txt](https://github.com/Azure/azure-iotedge/files/2746849/failed_logs_edgeHub_10_days_08_01_2019.txt)
[failed_logs_edgeHub_05012019.txt](https://github.com/Azure/azure-iotedge/files/2746850/failed_logs_edgeHub_05012019.txt)

Regards,
Prateek

**Comment by chipalost** [comment]
Hi @pratson20, please post this on the issues page for the IoT Edge open source project (https://github.com/azure/iotedge/issues). That is the source of our team's triage. We do not regularly check this page.
We understand that it is initially confusing to have two GitHub repos; however it is necessary for legal purposes.
Azure IoT Edge, open source project - https://github.com/azure/iotedge/
Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We try and do our coding in the open source project so that is why we request that issues are reported there.
