### ISSUE TITLE
windows arm version of moby?

### ISSUE THREAD

**Issue by StefanScherer** [Azure/azure-iotedge#17]
Hi @myagley,

I tried iotedge on a Raspberry Pi 3 and followed https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows and https://docs.microsoft.com/en-us/azure/iot-edge/quickstart to check if I can run Windows containers on it.
I hoped to get a moby engine for it to try the nanoserver image as I found a windows/arm variant in the manifest list. I'm just trying to connect the dots I see.
The install script downloads only the amd64 binaries.

No worries if it's in very early stage, I'm an early adopter of Windows containers and did something like this three years ago https://github.com/moby/moby/pull/18348, in the same time our Hypriot team pushed Docker on Raspberry Pi running on Linux. So I'm just curious how both worlds come together.

Thanks,
Stefan
Docker Captain, Microsoft MVP

**Comment by chipalost** [comment]
Hi @StefanScherer, we don't support Windows ARM32 at the moment; however please email me at cstreet@microsoft.com to discuss your scenario in greater depth.

In general, please post bugs on the issues page for the IoT Edge open source project (https://github.com/azure/iotedge/issues). That is the source of our team's triage. We do not regularly check this page.
We understand that it is initially confusing to have two GitHub repos; however it is necessary for legal purposes.
Azure IoT Edge, open source project - https://github.com/azure/iotedge/
Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We try and do our coding in the open source project so that is why we request that issues are reported there.
