### ISSUE TITLE
connection IOTedge to iothub device

### ISSUE THREAD

**Issue by Rahma1303** [Azure/azure-iotedge#22]
Hii 
i'm using linux Raspberry PI3 for C language...
i'm trying to connect my iothub device to my iotedge gateway...when using the IP address of the gateway hostname the connection works ...but when using the name ,like: 
connectionString ="HostName=iothub_host_name-;DeviceId=device_id;SharedAccessKey=device_key;GatewayHostName=edge-device-hostname"
it doesn't work...and i get the message error below
Press any key to continue
Error: Time:Thu Feb  7 09:45:27 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getaddrinfo failure -2.
Error: Time:Thu Feb  7 09:45:27 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
Error: Time:Thu Feb  7 09:45:27 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 09:45:27 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 09:45:27 2019 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Thu Feb  7 09:45:27 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2261 failure connecting to address iotedgegateway-device

**Comment by chipalost** [comment]
Hi @Rahma1303,  please post this on the issues page for the IoT Edge open source project (https://github.com/azure/iotedge/issues). That is the source of our team's triage. We do not regularly check this page.
We understand that it is initially confusing to have two GitHub repos; however it is necessary for legal purposes.
Azure IoT Edge, open source project - https://github.com/azure/iotedge/
Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We try and do our coding in the open source project so that is why we request that issues are reported there.
