### ISSUE TITLE
V1.0.4 offline parent/child

### ISSUE THREAD

**Issue by davebanthorpe** [Azure/azure-iotedge#7]
I have just deployed a new edge service on v1.0.4 (both agent and hub). I have configured an device that was previously talking direct to the main hub to be a child of the edge.

When I look at device explorer I never see any messages listed for edge, only for the device arriving at the hub. Do I need to change the connection string on the device now that it is a child of the edge - how does it know to send via the edge.

**Comment by chipalost** [comment]
Hi @davebanthorpe, please post this on the issues page for the IoT Edge open source project (https://github.com/azure/iotedge/issues).  That is the source of our team's triage. We do not regularly check this page.

We understand that it is initially confusing to have two GitHub repos; however it is necessary for legal purposes.
   * Azure IoT Edge, open source project - https://github.com/azure/iotedge/
   * Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We try and do our coding in the open source project so that is why we request that issues are reported there.
