### ISSUE TITLE
IoT Edge hub gets stuck and wont send messages upstream

### ISSUE THREAD

**Issue by robert4os** [Azure/azure-iotedge#9]
Hi,

on my PI3 the edgeHub module will get stuck every now and then with no apparent error or anything in the logs. 

The hub just stops sending messages to the iot hub. Actually in the portal it will show maybe one new message every 10 minutes or so. Instead of the 1 message per second I am sending usually. (Stream Analytics will report no messages.)

Only when I call 'docker container rm -f edgeHub'... will it resume to send messages.
(This 'fix' I found here https://github.com/AzureIoTGBB/azure-iot-edge-hol/blob/master/troubleshooting.md )

It already happened twice in the last week. 

The really annoying thing about it, is that there is now hint in the logs. I was looking at
'iotedge logs edgeHub' ...is there maybe another place to look for error messages? 

I using the latest release
Version - 1.0.4.18259757 (2835ac47fbb944ba628a5cfe812ff394768842e0)

Best regards, Robert

**Comment by carloshm** [comment]
see https://github.com/Azure/iotedge/issues/577

**Comment by chipalost** [comment]
Hi @robert4os, please post this on the issues page for the IoT Edge open source project (https://github.com/azure/iotedge/issues) if Azure/iotedge#577, as reccomended by carloshm, did not resolve your issue. The open source project is the source of our team's triage. We do not regularly check this page.

We understand that it is initially confusing to have two GitHub repos; however it is necessary for legal purposes.
   * Azure IoT Edge, open source project - https://github.com/azure/iotedge/
   * Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We try and do our coding in the open source project so that is why we request that issues are reported there.
